// <auto-generated />
using System;
using FbrSmartApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FbrSmartApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417062751_AddSaleServiceInfo")]
    partial class AddSaleServiceInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FbrSmartApp.Api.Models.AppRecordMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("MentionedUserIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SystemAction")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ResourceKey", "RecordKey");

                    b.ToTable("AppRecordMessages", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.ApprovalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ApprovalStatuses", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.ColorInfo", b =>
                {
                    b.Property<int>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorID"));

                    b.Property<string>("ColorTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryUserDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntryUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifyUserDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifyUserID")
                        .HasColumnType("int");

                    b.HasKey("ColorID");

                    b.ToTable("adgen_ColorInfo", "dbo");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Companyid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyImage")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<bool>("EnableSandBox")
                        .HasColumnType("bit");

                    b.Property<string>("FaxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FbrProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("FbrTokenProduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrTokenSandBox")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<int?>("MainCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("NTNNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoBoxNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaleEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("St_Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_Condition_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_Condition_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_Condition_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GLCompany", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.CompanyChatterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyChatterMessages", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.CustomerParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PartyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressOne")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPersonMobile")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("FbrStatusActive")
                        .HasColumnType("bit");

                    b.Property<string>("NTNNO")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PartyBusinessLogo")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PartyBusinessName")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("PartyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneOne")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("SaleTaxRegNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("gen_PartiesInfo", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.DataRegisterCurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CurrencyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BaseCurrency")
                        .HasColumnType("bit");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CurrencyNo")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("CurrencyStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LogSourceID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("data_RegisterCurrency", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CustomerPartyId")
                        .HasColumnType("int");

                    b.Property<decimal>("DeliveryFees")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ExcelUniqueInvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("FbrInvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FbrLastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FbrLastResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FbrScenarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Returned")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Taxes")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalExTaxes")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ExcelUniqueInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("UX_FbrInvoices_Company_ExcelUniqueInvoiceId")
                        .HasFilter("[ExcelUniqueInvoiceId] IS NOT NULL");

                    b.ToTable("FbrInvoices", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrInvoiceChatterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FbrInvoiceChatterMessages", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("FbrSalesTaxRateId")
                        .HasColumnType("int");

                    b.Property<string>("FbrSalesTaxRateIdsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SroItemText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FbrInvoiceLines", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiDocType", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "DocTypeId");

                    b.ToTable("FbrPdiDocTypes", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiItemDescCode", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("HsCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "HsCode");

                    b.ToTable("FbrPdiItemDescCodes", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiProvince", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("StateProvinceCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "StateProvinceCode");

                    b.ToTable("FbrPdiProvinces", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiSaleTypeRate", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("TransTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<int>("OriginationSupplier")
                        .HasColumnType("int");

                    b.Property<int>("RateId")
                        .HasColumnType("int");

                    b.Property<string>("RateDesc")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("RateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "TransTypeId", "RateDate", "OriginationSupplier", "RateId");

                    b.ToTable("FbrPdiSaleTypeRates", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiSyncState", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("FbrPdiSyncState", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiTransType", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("TransTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "TransTypeId");

                    b.ToTable("FbrPdiTransTypes", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrPdiUom", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UomId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId", "UomId");

                    b.ToTable("FbrPdiUoms", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrProvinceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Provincename")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.HasKey("Id");

                    b.ToTable("Fbr_ProvinceData", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RateDesc")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("RateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("FbrRates");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSaleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FbrSaleTypes");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSalesTaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AffectBaseOfSubsequentTaxes")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IncludeInAnalyticCost")
                        .HasColumnType("bit");

                    b.Property<string>("IncludedInPrice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LabelOnInvoices")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LegalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("TaxComputation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TaxGroup")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxScope")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Label", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("FbrSalesTaxRates", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSalesTaxRateChatterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalesTaxRateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesTaxRateId");

                    b.ToTable("FbrSalesTaxRateChatterMessages", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FbrPdiTransTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ScenarioCode")
                        .IsUnique();

                    b.ToTable("FbrScenarios", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSroItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SroId")
                        .HasColumnType("int");

                    b.Property<string>("SroItemDesc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FbrSroItems");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSroSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SerNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SroDesc")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("FbrSroSchedules");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenBankInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BankInfoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BankAccountNumber");

                    b.Property<string>("BankAccountTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BankAccountTitle");

                    b.Property<string>("BankAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BankAddress");

                    b.Property<string>("BankBranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BankBranchCode");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BankName");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime?>("EntryUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EntryUserDateTime");

                    b.Property<int?>("EntryUserId")
                        .HasColumnType("int")
                        .HasColumnName("EntryUserID");

                    b.Property<int?>("GlcaId")
                        .HasColumnType("int")
                        .HasColumnName("GLCAID");

                    b.Property<DateTime?>("ModifyUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyUserDateTime");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifyUserID");

                    b.Property<bool>("ValidateChequeBook")
                        .HasColumnType("bit")
                        .HasColumnName("ValidateChequeBook");

                    b.HasKey("Id");

                    b.HasIndex("GlcaId");

                    b.ToTable("gen_BankInformation", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenBranchInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BranchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BranchAddress");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BranchCode");

                    b.Property<string>("BranchDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BranchDescription");

                    b.Property<string>("BranchEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BranchEmail");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BranchName");

                    b.Property<string>("BranchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BranchNumber");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime?>("EntryUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EntryUserDateTime");

                    b.Property<int?>("EntryUserId")
                        .HasColumnType("int")
                        .HasColumnName("EntryUserID");

                    b.Property<DateTime?>("ModifyUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyUserDateTime");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifyUserID");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("gen_BranchInfo", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCashInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CashInfoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AccountTitle");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchID");

                    b.Property<int?>("CashAccount")
                        .HasColumnType("int")
                        .HasColumnName("CashAccount");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime?>("EntryUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EntryUserDateTime");

                    b.Property<int?>("EntryUserId")
                        .HasColumnType("int")
                        .HasColumnName("EntryUserID");

                    b.Property<DateTime?>("ModifyUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyUserDateTime");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifyUserID");

                    b.HasKey("Id");

                    b.HasIndex("CashAccount");

                    b.ToTable("gen_CashInformation", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCashInformationUser", b =>
                {
                    b.Property<int>("CashInfoId")
                        .HasColumnType("int")
                        .HasColumnName("CashInfoID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("CashInfoId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("gen_CashInformationUser", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCheckBookCancelledSerial", b =>
                {
                    b.Property<int>("CheckBookId")
                        .HasColumnType("int")
                        .HasColumnName("CheckBookID");

                    b.Property<decimal>("SerialNo")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("SerialNo");

                    b.HasKey("CheckBookId", "SerialNo");

                    b.ToTable("gen_CheckBookCancelledSerial", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCheckBookInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CheckBookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("BankId");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchID");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime?>("EntryUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("EntryUserDateTime");

                    b.Property<int?>("EntryUserId")
                        .HasColumnType("int")
                        .HasColumnName("EntryUserID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("ModifyUserDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifyUserDateTime");

                    b.Property<int?>("ModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifyUserID");

                    b.Property<decimal?>("SerialNoEnd")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("SerialNoEnd");

                    b.Property<decimal?>("SerialNoStart")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("SerialNoStart");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("gen_CheckBookInfo", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlAccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("DisplayOrder")
                        .HasColumnType("tinyint")
                        .HasColumnName("OrderBy");

                    b.Property<int?>("MainParentId")
                        .HasColumnType("int")
                        .HasColumnName("MainParent");

                    b.Property<string>("ReportingHead")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ReportingHead");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("GLAccontType", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlChartOfAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GLCAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountCurrency");

                    b.Property<string>("AccountLevelEight")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelEight");

                    b.Property<string>("AccountLevelFive")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelFive");

                    b.Property<string>("AccountLevelFour")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelFour");

                    b.Property<string>("AccountLevelNine")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelNine");

                    b.Property<string>("AccountLevelOne")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelOne");

                    b.Property<string>("AccountLevelSeven")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelSeven");

                    b.Property<string>("AccountLevelSix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelSix");

                    b.Property<string>("AccountLevelTen")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelTen");

                    b.Property<string>("AccountLevelThree")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountlevelThree");

                    b.Property<string>("AccountLevelTwo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountLevelTwo");

                    b.Property<bool>("AllowReconciliation")
                        .HasColumnType("bit")
                        .HasColumnName("AllowReconciliation");

                    b.Property<string>("ChartAccountGroupKey")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("ChartAccountGroupKey");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("Companyid");

                    b.Property<string>("EntryBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EntryBy");

                    b.Property<int?>("FiscalId")
                        .HasColumnType("int")
                        .HasColumnName("Fiscalid");

                    b.Property<int?>("GlBsId")
                        .HasColumnType("int")
                        .HasColumnName("GLBSid");

                    b.Property<string>("GlCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GLCode");

                    b.Property<byte?>("GlLevel")
                        .HasColumnType("tinyint")
                        .HasColumnName("GLLevel");

                    b.Property<byte?>("GlNature")
                        .HasColumnType("tinyint")
                        .HasColumnName("GLNature");

                    b.Property<int?>("GlPlId")
                        .HasColumnType("int")
                        .HasColumnName("GLPLid");

                    b.Property<string>("GlTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GLTitle");

                    b.Property<int?>("GlType")
                        .HasColumnType("int")
                        .HasColumnName("GLType");

                    b.Property<int?>("IsParent")
                        .HasColumnType("int")
                        .HasColumnName("isParent");

                    b.Property<string>("OldGlCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OLDGLCODE");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit")
                        .HasColumnName("ReadOnly");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("GLChartOFAccount", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlChartOfAccountBranchDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GLCABranchDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchID");

                    b.Property<int?>("GlcaId")
                        .HasColumnType("int")
                        .HasColumnName("GLCAID");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("GlcaId");

                    b.ToTable("GLChartOfAccountBranchDetail", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cr")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("cr");

                    b.Property<decimal>("Dr")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("dr");

                    b.Property<int?>("FbrSalesTaxRateId")
                        .HasColumnType("int")
                        .HasColumnName("FbrSalesTaxRateId");

                    b.Property<string>("FbrSalesTaxRateIdsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FbrSalesTaxRateIdsJson");

                    b.Property<int>("GlAccountId")
                        .HasColumnType("int")
                        .HasColumnName("GlAccountID");

                    b.Property<bool>("IsLog")
                        .HasColumnType("bit")
                        .HasColumnName("IsLog");

                    b.Property<string>("Narration")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Narration");

                    b.Property<string>("PartnerRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PartnerRef");

                    b.Property<int?>("PartyId")
                        .HasColumnType("int")
                        .HasColumnName("PartyID");

                    b.Property<int>("PrBookNo")
                        .HasColumnType("int")
                        .HasColumnName("PRBookNo");

                    b.Property<int?>("SchemeId")
                        .HasColumnType("int")
                        .HasColumnName("SchemeId");

                    b.Property<bool>("ShowToParty")
                        .HasColumnType("bit")
                        .HasColumnName("ShowToParty");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("TaxAmount");

                    b.Property<int>("VoucherMainId")
                        .HasColumnType("int")
                        .HasColumnName("vID");

                    b.HasKey("Id");

                    b.HasIndex("GlAccountId");

                    b.HasIndex("VoucherMainId");

                    b.ToTable("GLvDetail", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStatusId");

                    b.Property<int?>("BankCashGlAccountId")
                        .HasColumnType("int")
                        .HasColumnName("BankCashGlAccountId");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("BranchID");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit")
                        .HasColumnName("vCancel");

                    b.Property<DateTime?>("ChequeDate")
                        .HasColumnType("date")
                        .HasColumnName("ChequeDate");

                    b.Property<string>("ChequeNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ChequeNo");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("Comp_Id");

                    b.Property<DateTime>("EnteredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("vEnterDate");

                    b.Property<int?>("FiscalId")
                        .HasColumnType("int")
                        .HasColumnName("FiscalID");

                    b.Property<int>("LogSourceId")
                        .HasColumnType("int")
                        .HasColumnName("LogSourceID");

                    b.Property<string>("ManualNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ManualNo");

                    b.Property<bool>("Posted")
                        .HasColumnType("bit")
                        .HasColumnName("vPost");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("vPostedByDate");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vPostedByUserId");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit")
                        .HasColumnName("ReadOnly");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("vremarks");

                    b.Property<decimal?>("TotalCr")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("TotalCr");

                    b.Property<decimal?>("TotalDr")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("TotalDr");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("date")
                        .HasColumnName("vDate");

                    b.Property<string>("VoucherNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vNO");

                    b.Property<int>("VoucherTypeId")
                        .HasColumnType("int")
                        .HasColumnName("vType");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusId");

                    b.HasIndex("BankCashGlAccountId");

                    b.HasIndex("VoucherTypeId");

                    b.ToTable("GLvMAIN", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Voucherid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Companyid")
                        .HasColumnType("int");

                    b.Property<byte?>("ControlAccountTxnNature")
                        .HasColumnType("tinyint");

                    b.Property<int?>("CurrencyID")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultControlGlAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultIncomeGlAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentPrefix")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EntryBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("InterTransferPolicy")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowBankAndChequeDate")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowToAccountBook")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowToPartyV")
                        .HasColumnType("bit");

                    b.Property<string>("SignatureName1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SignatureName2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SignatureName3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SignatureName4")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("SignatureSlotCount")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("SystemType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("DefaultControlGlAccountId");

                    b.HasIndex("DefaultIncomeGlAccountId");

                    b.ToTable("GLVoucherType", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GroupAccessRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRead")
                        .HasColumnType("bit");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PermissionsPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("GroupAccessRights", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GroupMenuGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SecurityGroupId", "MenuKey")
                        .IsUnique();

                    b.ToTable("GroupMenuGrants", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GroupRecordRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApplyCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyRead")
                        .HasColumnType("bit");

                    b.Property<bool>("ApplyWrite")
                        .HasColumnType("bit");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Operator")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PermissionsPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RightOperandJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("GroupRecordRules", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.ProductProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FbrPdiTransTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FbrProductType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("FbrUomId")
                        .HasColumnType("int");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("RateId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RateValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SaleTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SroId")
                        .HasColumnType("int");

                    b.Property<int?>("SroItemId")
                        .HasColumnType("int");

                    b.Property<string>("SroItemRefText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SroScheduleNoText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "ProductNo")
                        .IsUnique();

                    b.ToTable("ProductProfiles");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.ProductProfileChatterMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductProfileId");

                    b.ToTable("ProductProfileChatterMessages", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.RecordRuleModelFieldSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModelKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PermissionsPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionsPrefix", "ModelKey", "FieldName")
                        .IsUnique();

                    b.ToTable("RecordRuleModelFieldSettings", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.SecurityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ApiKeysMaxDurationDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationScope")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShareGroup")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Name");

                    b.ToTable("SecurityGroups", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.SecurityGroupInheritance", b =>
                {
                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ParentSecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("SecurityGroupId", "ParentSecurityGroupId");

                    b.HasIndex("ParentSecurityGroupId");

                    b.ToTable("SecurityGroupInheritances", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessRightsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedCompanyIdsJson")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CalendarDefaultPrivacy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailSignature")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationChannel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("OnboardingEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PermissionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.UserSecurityGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SecurityGroupId");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("UserSecurityGroups", (string)null);
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrInvoiceChatterMessage", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.FbrInvoice", "Invoice")
                        .WithMany("ChatterMessages")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrInvoiceLine", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.FbrInvoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSalesTaxRateChatterMessage", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.FbrSalesTaxRate", null)
                        .WithMany("ChatterMessages")
                        .HasForeignKey("SalesTaxRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenBankInformation", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.GlChartOfAccount", "GlAccount")
                        .WithMany()
                        .HasForeignKey("GlcaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GlAccount");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCashInformation", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.GlChartOfAccount", "GlAccount")
                        .WithMany()
                        .HasForeignKey("CashAccount")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GlAccount");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCashInformationUser", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.GenCashInformation", "CashInformation")
                        .WithMany("AllowedUsers")
                        .HasForeignKey("CashInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FbrSmartApp.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashInformation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCheckBookCancelledSerial", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.GenCheckBookInfo", "CheckBook")
                        .WithMany("CancelledSerials")
                        .HasForeignKey("CheckBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckBook");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCheckBookInfo", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.GenBankInformation", "Bank")
                        .WithMany("CheckBooks")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherDetail", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.GlChartOfAccount", "GlAccount")
                        .WithMany()
                        .HasForeignKey("GlAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FbrSmartApp.Api.Models.GlVoucherMain", "VoucherMain")
                        .WithMany("Details")
                        .HasForeignKey("VoucherMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlAccount");

                    b.Navigation("VoucherMain");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherMain", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.ApprovalStatus", "ApprovalStatus")
                        .WithMany()
                        .HasForeignKey("ApprovalStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FbrSmartApp.Api.Models.GlChartOfAccount", "BankCashGlAccount")
                        .WithMany()
                        .HasForeignKey("BankCashGlAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FbrSmartApp.Api.Models.GlVoucherType", "VoucherType")
                        .WithMany()
                        .HasForeignKey("VoucherTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalStatus");

                    b.Navigation("BankCashGlAccount");

                    b.Navigation("VoucherType");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherType", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.DataRegisterCurrency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FbrSmartApp.Api.Models.GlChartOfAccount", "DefaultControlGlAccount")
                        .WithMany()
                        .HasForeignKey("DefaultControlGlAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FbrSmartApp.Api.Models.GlChartOfAccount", "DefaultIncomeGlAccount")
                        .WithMany()
                        .HasForeignKey("DefaultIncomeGlAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currency");

                    b.Navigation("DefaultControlGlAccount");

                    b.Navigation("DefaultIncomeGlAccount");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GroupAccessRight", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("AccessRights")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GroupMenuGrant", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("MenuGrants")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GroupRecordRule", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("RecordRules")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.ProductProfileChatterMessage", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.ProductProfile", null)
                        .WithMany("ChatterMessages")
                        .HasForeignKey("ProductProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.SecurityGroupInheritance", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.SecurityGroup", "ParentGroup")
                        .WithMany()
                        .HasForeignKey("ParentSecurityGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FbrSmartApp.Api.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("ParentLinks")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentGroup");

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.UserSecurityGroup", b =>
                {
                    b.HasOne("FbrSmartApp.Api.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("UserLinks")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FbrSmartApp.Api.Models.User", "User")
                        .WithMany("SecurityGroupLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrInvoice", b =>
                {
                    b.Navigation("ChatterMessages");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.FbrSalesTaxRate", b =>
                {
                    b.Navigation("ChatterMessages");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenBankInformation", b =>
                {
                    b.Navigation("CheckBooks");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCashInformation", b =>
                {
                    b.Navigation("AllowedUsers");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GenCheckBookInfo", b =>
                {
                    b.Navigation("CancelledSerials");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.GlVoucherMain", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.ProductProfile", b =>
                {
                    b.Navigation("ChatterMessages");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.SecurityGroup", b =>
                {
                    b.Navigation("AccessRights");

                    b.Navigation("MenuGrants");

                    b.Navigation("ParentLinks");

                    b.Navigation("RecordRules");

                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("FbrSmartApp.Api.Models.User", b =>
                {
                    b.Navigation("SecurityGroupLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
