// <auto-generated/>
// Generated by scripts/generate-permission-catalog.mjs from shared/permission-catalog.manifest.json
namespace FbrSmartApp.Api.Services;

internal static class PermissionCatalogGenerated
{
    internal static readonly IReadOnlyList<PermissionCatalog.AppCatalogEntry> Apps =
    [
        new PermissionCatalog.AppCatalogEntry(
            "fbr-smart",
            "fbr",
            "FBR Smart",
            [
                new PermissionCatalog.ResourceEntry("customers", "Customers"),
                new PermissionCatalog.ResourceEntry("fbrInvoices", "FBR Invoices"),
                new PermissionCatalog.ResourceEntry("products", "Products"),
                new PermissionCatalog.ResourceEntry("productProfiles", "Product profiles"),
                new PermissionCatalog.ResourceEntry("fbrScenarios", "FBR scenarios"),
                new PermissionCatalog.ResourceEntry("fbrSalesTaxRates", "Sales tax rates"),
                new PermissionCatalog.ResourceEntry("companies", "Companies"),
                new PermissionCatalog.ResourceEntry("categories", "Categories"),
                new PermissionCatalog.ResourceEntry("reviews", "Reviews"),
            ]),
        new PermissionCatalog.AppCatalogEntry(
            "accounting-suite",
            "accounting",
            "Accounting",
            [
                new PermissionCatalog.ResourceEntry("glChartAccounts", "Chart of accounts"),
                new PermissionCatalog.ResourceEntry("glVoucherTypes", "Voucher types"),
                new PermissionCatalog.ResourceEntry("glJournalVouchers", "Journal vouchers"),
                new PermissionCatalog.ResourceEntry("glAccountTypes", "GL account types"),
                new PermissionCatalog.ResourceEntry("accountingReports", "Accounting reports"),
                new PermissionCatalog.ResourceEntry("customers", "Customers"),
                new PermissionCatalog.ResourceEntry("genBankInformation", "Bank information"),
                new PermissionCatalog.ResourceEntry("genCashInformation", "Cash information"),
            ]),
        new PermissionCatalog.AppCatalogEntry(
            "settings",
            "settings",
            "Settings",
            [
                new PermissionCatalog.ResourceEntry("securityGroups", "Security groups"),
                new PermissionCatalog.ResourceEntry("users", "Users"),
            ]),
        new PermissionCatalog.AppCatalogEntry(
            "auto-dealers",
            "auto-dealers",
            "Auto Dealers",
            [
                new PermissionCatalog.ResourceEntry("securityGroups", "Security groups"),
                new PermissionCatalog.ResourceEntry("users", "Users"),
            ]),
    ];
}
